apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: todo-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
      - name: frontend

        image: swagnik10/todo-frontend:1.1

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"

        ports:
        - containerPort: 80