apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: todo-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
      - name: backend

        image: swagnik10/todo-backend:v2

        ports:
        - containerPort: 8080

        volumeMounts:
        - name: backend-logs
          mountPath: /app/logs

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"

        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Docker"

        - name: ASPNETCORE_URLS
          value: "http://+:8080"

        - name: ConnectionStrings__DefaultConnection
          value: "Server=sqlserver;Database=Todo;User Id=sa;Password=YourStrongPassword123!;TrustServerCertificate=True;"

      volumes:
      - name: backend-logs
        persistentVolumeClaim:
          claimName: backend-logs-pvc